image: rocker/tidyverse

test:
  script:
    - R -e 'devtools::install_github("ThinkR-open/golem")'
    - R -e 'devtools::install_deps(dependencies = TRUE)'
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check *tar.gz --no-build-vignettes --no-manual
