image: r-base

test:
  script:
    - R -e "install.packages('devtools')"
    - R -e 'devtools::install_deps(dependencies = TRUE)'
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check *tar.gz --no-build-vignettes --no-manual
